name: grabtube
description: A cutting-edge multi-platform tube services downloader with modern UI/UX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.4

  # Network
  dio: ^5.7.0
  socket_io_client: ^2.0.3+1
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.2

  # Platform Integration
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2

  # Notifications
  flutter_local_notifications: ^18.0.1

  # Background Tasks
  workmanager: ^0.5.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.4.0
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1

  # Reactive Programming
  rxdart: ^0.28.0

  # Functional Programming
  dartz: ^0.10.1

  # Video Player (for preview)
  video_player: ^2.9.1

  # File Handling
  open_file: ^3.5.3
  file_picker: ^8.1.2

  # QR Code Scanning
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  js: ^0.6.7
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  patrol: ^3.11.2
  integration_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # Analysis
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

  # App Icons & Splash
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.jpeg"
  windows:
    generate: true
    image_path: "assets/images/logo.jpeg"
  macos:
    generate: true
    image_path: "assets/images/logo.jpeg"
  linux:
    generate: true
    image_path: "assets/images/logo.jpeg"
  web:
    generate: true
    image_path: "assets/images/logo.jpeg"
    background_color: "#FFFFFF"
    theme_color: "#E74C3C"

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.jpeg"
  android: true
  ios: true
  web: true

  android_12:
    color: "#FFFFFF"
    image: "assets/images/logo.jpeg"

  # Platform-specific splash screens
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  # Brand colors from logo
  color_dark: "#2C3E50"
  image_dark: "assets/images/logo.jpeg"

  android_12_dark:
    color: "#2C3E50"
    image: "assets/images/logo.jpeg"
