// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by running: flutter pub run build_runner build

// ignore_for_file: unnecessary_lambdas
// ignore_for_file: lines_longer_than_80_chars
// coverage:ignore-file

import 'package:get_it/get_it.dart' as _i1;
import 'package:injectable/injectable.dart' as _i2;

extension GetItInjectableX on _i1.GetIt {
  _i1.GetIt init({
    String? environment,
    _i2.EnvironmentFilter? environmentFilter,
  }) {
    // This will be auto-generated after running build_runner
    return this;
  }
}
