name: grabtube_web
description: GrabTube Flutter Web Client - Modern web interface for yt-dlp downloads
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.4

  # Network
  dio: ^5.7.0
  socket_io_client: ^2.0.3+1
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Local Storage (Web Compatible)
  shared_preferences: ^2.3.2
  shared_preferences_web: ^2.4.2

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.4.0
  url_launcher: ^6.3.1
  url_launcher_web: ^2.3.3

  # Reactive Programming
  rxdart: ^0.28.0

  # Responsive Design
  responsive_framework: ^1.5.1

  # Web Utilities
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0

  # Analysis
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
