// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by running: flutter pub run build_runner build

part of 'api_client.dart';

// Placeholder for generated Retrofit implementation
class _ApiClient implements ApiClient {
  _ApiClient(this._dio);

  final Dio _dio;

  @override
  Future<Map<String, dynamic>> addDownload({
    required String url,
    String? quality,
    String? format,
    String? folder,
    bool? autoStart,
  }) async {
    const path = '/add';
    final data = {
      'url': url,
      if (quality != null) 'quality': quality,
      if (format != null) 'format': format,
      if (folder != null) 'folder': folder,
      if (autoStart != null) 'auto_start': autoStart,
    };
    final response = await _dio.post<Map<String, dynamic>>(path, data: data);
    return response.data!;
  }

  @override
  Future<Map<String, dynamic>> getDownloads() async {
    const path = '/downloads';
    final response = await _dio.get<Map<String, dynamic>>(path);
    return response.data!;
  }

  @override
  Future<List<DownloadModel>> getQueue() async {
    const path = '/queue';
    final response = await _dio.get<List<dynamic>>(path);
    return response.data!
        .map((e) => DownloadModel.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<List<DownloadModel>> getCompleted() async {
    const path = '/done';
    final response = await _dio.get<List<dynamic>>(path);
    return response.data!
        .map((e) => DownloadModel.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<List<DownloadModel>> getPending() async {
    const path = '/pending';
    final response = await _dio.get<List<dynamic>>(path);
    return response.data!
        .map((e) => DownloadModel.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<Map<String, dynamic>> deleteDownload({
    required List<String> ids,
    String where = 'queue',
  }) async {
    const path = '/delete';
    final data = {'ids': ids, 'where': where};
    final response = await _dio.post<Map<String, dynamic>>(path, data: data);
    return response.data!;
  }

  @override
  Future<Map<String, dynamic>> startDownload({required List<String> ids}) async {
    const path = '/start';
    final data = {'ids': ids};
    final response = await _dio.post<Map<String, dynamic>>(path, data: data);
    return response.data!;
  }

  @override
  Future<List<DownloadModel>> getHistory() async {
    const path = '/history';
    final response = await _dio.get<List<dynamic>>(path);
    return response.data!
        .map((e) => DownloadModel.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<Map<String, dynamic>> clearCompleted() async {
    const path = '/clear';
    final response = await _dio.post<Map<String, dynamic>>(path);
    return response.data!;
  }

  @override
  Future<Map<String, dynamic>> getVideoInfo({required String url}) async {
    const path = '/info';
    final response = await _dio.get<Map<String, dynamic>>(
      path,
      queryParameters: {'url': url},
    );
    return response.data!;
  }

  @override
  Future<Map<String, dynamic>> checkHealth() async {
    const path = '/health';
    final response = await _dio.get<Map<String, dynamic>>(path);
    return response.data!;
  }
}
