// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by running: flutter pub run build_runner build

part of 'download_model.dart';

// Placeholder - will be generated by json_serializable
DownloadModel _$DownloadModelFromJson(Map<String, dynamic> json) =>
    DownloadModel(
      id: json['id'] as String,
      url: json['url'] as String,
      title: json['title'] as String,
      status: json['status'] as String,
      thumbnail: json['thumbnail'] as String?,
      folder: json['folder'] as String?,
      quality: json['quality'] as String?,
      format: json['format'] as String?,
      progress: (json['progress'] as num?)?.toDouble(),
      speed: json['speed'] as String?,
      eta: json['eta'] as String?,
      fileSize: (json['total_bytes'] as num?)?.toInt(),
      downloadedSize: (json['downloaded_bytes'] as num?)?.toInt(),
      error: json['error'] as String?,
      timestamp: json['timestamp'] as String?,
    );

Map<String, dynamic> _$DownloadModelToJson(DownloadModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'url': instance.url,
      'title': instance.title,
      'status': instance.status,
      'thumbnail': instance.thumbnail,
      'folder': instance.folder,
      'quality': instance.quality,
      'format': instance.format,
      'progress': instance.progress,
      'speed': instance.speed,
      'eta': instance.eta,
      'total_bytes': instance.fileSize,
      'downloaded_bytes': instance.downloadedSize,
      'error': instance.error,
      'timestamp': instance.timestamp,
    };
